#!/usr/bin/env bash

# Git and GitHub API manager for Antigravity Builder
# Handles branching, committing, pushing, PR creation, and label removal.

set -euo pipefail

# Verify required parameters for GitHub API interactions
verify_github_env() {
  if [ -z "${GITHUB_PAT:-}" ]; then
    echo "Error: GITHUB_PAT environment variable is not set." >&2
    exit 1
  fi
  if [ -z "${GITHUB_REPOSITORY:-}" ]; then
    echo "Error: GITHUB_REPOSITORY environment variable is not set." >&2
    exit 1
  fi
  
  # Normalize GITHUB_REPOSITORY to owner/repo format
  local CLEAN_REPO="${GITHUB_REPOSITORY}"
  CLEAN_REPO="${CLEAN_REPO#http://github.com/}"
  CLEAN_REPO="${CLEAN_REPO#https://github.com/}"
  CLEAN_REPO="${CLEAN_REPO%.git}"
  GITHUB_REPOSITORY="$CLEAN_REPO"
}

ACTION="${1:-}"
if [ -z "$ACTION" ]; then
  echo "Usage: $0 <action> [arguments...]" >&2
  echo "Actions: checkout_base, create_branch, check_changes, commit_and_push, create_pr, remove_label" >&2
  exit 1
fi

BASE_BRANCH="${BASE_BRANCH:-main}"
LABEL="${ISSUE_LABEL:-antigravity}"

# Resolve and switch to project directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${PROJECT_DIR:-$(dirname "$SCRIPT_DIR")}"
cd "$TARGET_DIR"

case "$ACTION" in
  checkout_base)
    echo "Checking out base branch: $BASE_BRANCH" >&2
    git checkout "$BASE_BRANCH"
    git pull origin "$BASE_BRANCH" || echo "Warning: Could not pull latest changes from remote. Continuing." >&2
    ;;

  create_branch)
    if [ "$#" -lt 2 ]; then
      echo "Usage: $0 create_branch <issue_number>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"
    BRANCH_NAME="issue-$ISSUE_NUMBER"
    echo "Creating and checking out branch: $BRANCH_NAME" >&2
    # Checkout branch if exists, otherwise create it
    if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
      git checkout "$BRANCH_NAME"
    else
      git checkout -b "$BRANCH_NAME"
    fi
    ;;

  check_changes)
    # Check if there are modified or untracked files
    if [ -n "$(git status --porcelain)" ]; then
      echo "Changes detected." >&2
      exit 0
    else
      echo "No changes detected." >&2
      exit 1
    fi
    ;;

  commit_and_push)
    if [ "$#" -lt 3 ]; then
      echo "Usage: $0 commit_and_push <issue_number> <issue_title>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"
    ISSUE_TITLE="$3"
    BRANCH_NAME="issue-$ISSUE_NUMBER"

    echo "Staging files..." >&2
    git add .
    
    echo "Committing changes..." >&2
    git commit -m "Fix #$ISSUE_NUMBER: $ISSUE_TITLE"
    
    echo "Pushing branch $BRANCH_NAME to origin..." >&2
    git push -u origin "$BRANCH_NAME" --force
    ;;

  create_pr)
    verify_github_env
    if [ "$#" -lt 3 ]; then
      echo "Usage: $0 create_pr <issue_number> <issue_title>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"
    ISSUE_TITLE="$3"
    BRANCH_NAME="issue-$ISSUE_NUMBER"

    echo "Creating Pull Request on GitHub..." >&2
    PR_PAYLOAD=$(jq -n \
      --arg title "Fix #$ISSUE_NUMBER: $ISSUE_TITLE" \
      --arg head "$BRANCH_NAME" \
      --arg base "$BASE_BRANCH" \
      --arg body "Linked Issue: #$ISSUE_NUMBER

This Pull Request was automatically generated by Antigravity to resolve the issue." \
      '{title: $title, head: $head, base: $base, body: $body}')

    PR_RESPONSE=$(curl -s \
      -H "Authorization: token $GITHUB_PAT" \
      -H "Accept: application/vnd.github.v3+json" \
      -d "$PR_PAYLOAD" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls")

    # Check if PR was created successfully
    PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url // empty')
    if [ -n "$PR_URL" ]; then
      echo "Pull Request successfully created: $PR_URL" >&2
      echo "$PR_URL"
    else
      # Check if the PR already exists (idempotency)
      if echo "$PR_RESPONSE" | grep -q "A pull request already exists"; then
        echo "A Pull Request already exists for this branch on GitHub. Continuing." >&2
      else
        ERR_MSG=$(echo "$PR_RESPONSE" | jq -r '.message // "Unknown error"')
        echo "Error creating Pull Request: $ERR_MSG" >&2
        exit 1
      fi
    fi
    ;;

  remove_label)
    verify_github_env
    if [ "$#" -lt 2 ]; then
      echo "Usage: $0 remove_label <issue_number>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"

    echo "Removing label '$LABEL' from issue #$ISSUE_NUMBER..." >&2
    # Encode label for URL path
    ENCODED_LABEL=$(jq -rn --arg lbl "$LABEL" '$lbl | @uri')
    
    # We do not use -f here so that it doesn't fail hard if the label was not present.
    curl -s -X DELETE \
      -H "Authorization: token $GITHUB_PAT" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/labels/$ENCODED_LABEL" > /dev/null || true
    echo "Label removed." >&2

    # Add 'qa' label to notify for testing
    echo "Adding label 'qa' to issue #$ISSUE_NUMBER..." >&2
    curl -s -X POST \
      -H "Authorization: token $GITHUB_PAT" \
      -H "Accept: application/vnd.github.v3+json" \
      -d '{"labels": ["qa"]}' \
      "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/labels" > /dev/null || true
    echo "Label 'qa' added." >&2
    ;;

  commit_local)
    if [ "$#" -lt 3 ]; then
      echo "Usage: $0 commit_local <issue_number> <issue_title>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"
    ISSUE_TITLE="$3"

    echo "Staging files..." >&2
    git add .
    
    echo "Committing changes locally..." >&2
    git commit -m "Fix #$ISSUE_NUMBER: $ISSUE_TITLE"
    ;;

  merge_and_push_base)
    if [ "$#" -lt 2 ]; then
      echo "Usage: $0 merge_and_push_base <issue_number>" >&2
      exit 1
    fi
    ISSUE_NUMBER="$2"
    BRANCH_NAME="issue-$ISSUE_NUMBER"

    echo "Checking out base branch '$BASE_BRANCH'..." >&2
    git checkout "$BASE_BRANCH"

    echo "Pulling latest changes on '$BASE_BRANCH'..." >&2
    git pull origin "$BASE_BRANCH" || true

    echo "Merging branch '$BRANCH_NAME' into '$BASE_BRANCH'..." >&2
    git merge "$BRANCH_NAME" --no-edit

    echo "Pushing '$BASE_BRANCH' to origin..." >&2
    git push origin "$BASE_BRANCH"

    echo "Cleaning up local issue branch '$BRANCH_NAME'..." >&2
    git branch -d "$BRANCH_NAME" || git branch -D "$BRANCH_NAME"
    ;;

  *)
    echo "Unknown action: $ACTION" >&2
    exit 1
    ;;
esac
